name: "Angular Elements experiments CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        angular-version:
          - 9.0.x
          # - 9.1.x
          - 10.0.x
          - 10.1.x
          # - 10.2.x
          - 11.0.x
          # - 11.1.x
          # - 11.2.x

    steps:
      # Source code
      - uses: actions/checkout@v2

      # Set up environment
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: ngworker/angular-versions-action@v3
        with:
          angular-version: ${{ matrix.angular-version }}
      - uses: ./.github/actions/package-version
        with:
          name: "ngx-build-plus"
          version: ${{ matrix.angular-version }}

      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile false --verify-store-integrity false

      # Perform the action
      - run: pnpm build
