name: "Angular Elements experiments CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Source code
      - uses: actions/checkout@v2

      # Set up environment
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn global add pnpm
      - run: pnpm install

      # Perform the action
      - run: pnpm build
